name: Deploy Branch to Dev

on:
  workflow_dispatch:

jobs:
  openjdk17:
    runs-on: ubuntu-24.04
    env:
      JAVA_OPTS: "-Xmx20g"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - name: Check if organization member
        id: check_org_member
        uses: Mind-Sports-Games/check-org-member@v1.1.0
        with:
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check Failed
        if: ${{ steps.check_org_member.outputs.result == 'false' }}
        run: |
          echo User Does Not Belong to Mind-Sports-Games
          exit 1
      - name: Check Passed
        run: echo The actor is an organization member
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/project/build.properties') }}-${{ hashFiles('**/build.sbt') }}-${{ hashFiles('**/project/Dependencies.scala') }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17.0.5
          cache: sbt
      - name: Setup sbt
        uses: sbt/setup-sbt@v1
      - run: sbt -Depoll=true "test;stage"
      - run: cp LICENSE README.md target/universal/stage && git log -n 1 --pretty=oneline > target/universal/stage/commit.txt
      - run: cd target/universal/stage && tar -cvpJf ../../../lila-ws-3.0.tar.xz . && cd -
        env:
          XZ_OPT: '-0'
      - uses: actions/upload-artifact@v4
        with:
          name: lila-ws
          path: lila-ws-3.0.tar.xz
      - name: Dev -- Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PSD_MAIN_HOST }}
          username: ${{ secrets.PSD_MAIN_USERNAME }}
          key: ${{ secrets.MSO_CI_SSH_KEY }}
          source: 'lila-ws-3.0.tar.xz'
          target: '/tmp/'
      - name: Dev -- Upgrade application
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: /opt/lila/upgrade.sh lila-ws /tmp/lila-ws-3.0.tar.xz
          host: ${{ secrets.PSD_MAIN_HOST }}
          username: ${{ secrets.PSD_MAIN_USERNAME }}
          privateKey: ${{ secrets.MSO_CI_SSH_KEY }}
  notify:
    runs-on: ubuntu-24.04
    env:
      WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_DEPLOY_DEV }}
    needs: openjdk17
    if: ${{ needs.openjdk17.result == 'success' }}
    steps:
      - name: Notify
        run: curl
          --request POST
          --data-urlencode "content=:white_check_mark: **lila-ws** branch <https://github.com/Mind-Sports-Games/lila-ws/tree/${GITHUB_REF##*/}> is on <https://playstrategy.dev>"
          $WEBHOOK_URL
