name: Test

on: [push, pull_request]

jobs:
  openjdk13:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17.0.5
    - run: sbt compile
